In [2]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [50]:
#tensors are immutable.
#tf.constant is immutable
#tf.variable is muttable
import tensorflow as tf
x=tf.constant(4,shape=(2,2),dtype=tf.float32)
print(x)

tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


In [9]:
x=tf.constant([1,2,3])
print("rank 1 " ,x)

y=tf.constant([[1,2,3],[4,5,6]])
print("\nrank 2 " ,y)

rank 1  tf.Tensor([1 2 3], shape=(3,), dtype=int32)

rank 2  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [13]:
x=tf.ones((3,3))
print("\n",x)



 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [14]:
y=tf.zeros((3,3))
print("\n",y)


 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [15]:
y=tf.eye(3)
print("\n",y)


 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
#uniform distribution
x=tf.random.uniform((3,3),minval=5,maxval=10)
print(x)

tf.Tensor(
[[7.3431087 7.73428   9.655867 ]
 [8.817854  8.095016  8.011998 ]
 [6.1324816 6.510103  5.034176 ]], shape=(3, 3), dtype=float32)


In [20]:
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[-1.6000836   1.5180688  -0.29534656]
 [-0.5035204   0.87748307  0.7065382 ]
 [-0.5903469  -0.68926084  0.5069956 ]], shape=(3, 3), dtype=float32)


In [22]:
x=tf.range(10)
print(x)

y=tf.cast(x,dtype=tf.float32)
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [23]:
#operations in tensorflow are elementwise
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])

In [24]:
c=a+b
d=tf.add(a,b)

print(c)
print("\n\n",d)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


 tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [25]:
c=a-b
d=tf.subtract(a,b)

print(c)
print("\n\n",d)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


 tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [26]:
c=a*b
d=tf.multiply(a,b)

print(c)
print("\n\n",d)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


 tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [28]:
c=a/b
d=tf.divide(a,b)
print(c)
print("\n\n",d)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


 tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [31]:
c=tf.tensordot(a,b,axes=1)
print(c)

tf.Tensor(32, shape=(), dtype=int32)


In [32]:
c= a ** 3
print(c) 

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [33]:
#matrix multiplication 
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))

print(x)
print("\n",y)


tf.Tensor(
[[ 1.9352764   0.9160396  -1.0772079 ]
 [ 0.20582496  0.55543363 -0.41472948]], shape=(2, 3), dtype=float32)

 tf.Tensor(
[[-5.7283008e-01  1.1305737e-01 -1.2685891e+00 -4.1322929e-01]
 [ 1.2051585e+00 -2.6560253e-01  3.8203070e-01  4.8571885e-01]
 [ 9.9565834e-01  6.0113013e-04  8.6420739e-01 -7.5392634e-01]], shape=(3, 4), dtype=float32)


In [36]:
z=tf.matmul(x,y)

u=x @ y
print(z)
print("\n",u)

tf.Tensor(
[[-1.0771427  -0.02515272 -3.0360463   0.4573602 ]
 [ 0.13855393 -0.12450385 -0.40732688  0.49740714]], shape=(2, 4), dtype=float32)

 tf.Tensor(
[[-1.0771427  -0.02515272 -3.0360463   0.4573602 ]
 [ 0.13855393 -0.12450385 -0.40732688  0.49740714]], shape=(2, 4), dtype=float32)


In [39]:
#slicing and indexing
x=tf.constant([[1,2,3,4],[5,6,7,8]])
print(x)
print("\n",x.shape)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)

 (2, 4)


In [40]:
print(x[0])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [41]:
print(x[0,:])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [42]:
print(x[:,0])

tf.Tensor([1 5], shape=(2,), dtype=int32)


In [43]:
print(x[:,2:4])

tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int32)


In [44]:
#reshaping
x=tf.constant([[1,2,3],[4,6,7]])
print(x)
print("\n",x.shape)

tf.Tensor(
[[1 2 3]
 [4 6 7]], shape=(2, 3), dtype=int32)

 (2, 3)


In [46]:
y=tf.reshape(x,(3,2))
print(y)

tf.Tensor(
[[1 2]
 [3 4]
 [6 7]], shape=(3, 2), dtype=int32)


In [48]:
y=tf.reshape(x,(6))
print(y)

tf.Tensor([1 2 3 4 6 7], shape=(6,), dtype=int32)


In [ ]:
y=tf.reshape(x,(7))# will give error: InvalidArgumentError: Input to reshape is a tensor with 6 values, but the requested shape has 7 [Op:Reshape]
print(y)

In [49]:
y=tf.reshape(x,(-1,2)) #-1 automatically takes best value to give op
print(y)

tf.Tensor(
[[1 2]
 [3 4]
 [6 7]], shape=(3, 2), dtype=int32)


In [60]:
#tensors to numpy
x=tf.constant([1,2,3])
print("\nx=",x)
print("\ntype is",type(x))

y=x.numpy()
print("\ny=",y)
print("\ntype is ",type(y))



x= tf.Tensor([1 2 3], shape=(3,), dtype=int32)

type is <class 'tensorflow.python.framework.ops.EagerTensor'>

y= [1 2 3]

type is  <class 'numpy.ndarray'>


In [61]:
#numpy to tensors
z=tf.convert_to_tensor(y)
print("\nz=",z)
print("\ntype is ",type(z))



z= tf.Tensor([1 2 3], shape=(3,), dtype=int32)

type is  <class 'tensorflow.python.framework.ops.EagerTensor'>


In [62]:
#string tensor
a=tf.constant(['patrik','jose'])
print(a)

tf.Tensor([b'patrik' b'jose'], shape=(2,), dtype=string)


In [64]:
a=tf.Variable([1,2,3])
print("\n",a)

print(type(a))
print(a.dtype)


 <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<dtype: 'int32'>
